# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nyumbani
author: Ibrahim Mkusa
description: >
  My ship on the vast digital sea
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ibrahimmkusa.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  iskm

# Build settings
theme: minima
minima:
  skin: solarized-dark
  social_links:
    - { platform: github,         user_url: "https://github.com/iskm"  }
    #- { platform: gitlab,         user_url: "https://gitlab.com/iskm"  }
plugins:
  - jekyll-feed
  - jekyll-seo-tag
