name: deploy tovuti
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    #- name: check and fix typos
      #uses: crate-ci/typos@v1.20.1
      #with:
        #files:
    #    write_changes: true

    # make available locally on runner via apt
    # - name: install ruby on runner
    # uses: ruby/setup-ruby@v1
    # with:
    # ruby-version: '3.1'
    # bundler-cache: true
    # - run: bundle exec rake
    - run: |
        bundle install --path ~/.gem
        bundle exec jekyll build
    - name: deploy
      env:
        SSH_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        user: ${{ secrets.USERNAME }}
        url: ${{ secrets.SERVER_URL }}
        location:  ${{ secrets.LOCATION }}
        gitea_user: ${{ secrets.GITEA_USER }}
        gitea_pass: ${{ secrets.GITEA_PASS }}
      run: |
        echo "$SSH_KEY" > ssh_key
        chmod 600 ssh_key
        rsync -avz -e "ssh -i ssh_key -o StrictHostKeyChecking=no" ./_site/ \
                                                                  $user@$url:$location
        rm ssh_key

    - name: deploy to gitea
      env:
        gitea_user: ${{ secrets.GITEA_USER }}
        gitea_pass: ${{ secrets.GITEA_PASS }}
      run: |
        docker login gitea.kwerezigua.org -u $gitea_user -p $gitea_pass
        docker build -t tovuti:latest  .
        docker tag tovuti:latest gitea.kwerezigua.org/iskm/tovuti:latest
        docker push gitea.kwerezigua.org/iskm/tovuti:latest

    - name: deploy to harbor
      env:
        gitea_user: ${{ secrets.GITEA_USER }}
        gitea_pass: ${{ secrets.GITEA_PASS }}
      run: |
        docker login harbor.kwerezigua.org -u $gitea_user -p $gitea_pass
        docker tag gitea.kwerezigua.org/iskm/tovuti:latest harbor.kwerezigua.org/iskm/tovuti:latest
        docker push harbor.kwerezigua.org/iskm/tovuti:latest
